wallpaper {
    monitor = HDMI-A-1
    path = /home/afk/Images/wallpapers/fog_forest_1.png
    fit_mode = fill
}

wallpaper {
    monitor = DP-1
    path = /home/afk/Images/wallpapers/fog_forest_alt_1.png
    fit_mode = fill
}

splash = false
ipc = off
